---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "frr_router"
    static_configs:
      - targets: ["172.20.20.13:9342"]  # frr-exporter port
  - job_name: "srlinux_nodes"
    static_configs:
      - targets: ["172.20.20.11:9115", "172.20.20.12:9115"]  # gnmi/snmp exporter
