frr version 9.1
frr defaults traditional
hostname frr01
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 ip address 10.1.13.2/24
!
interface eth2
 ip address 10.1.23.2/24
!
interface lo
 ip address 10.0.0.3/32
!
router bgp 65002
 bgp router-id 10.0.0.3
 no bgp ebgp-requires-policy
 neighbor 10.1.13.1 remote-as 65001
 neighbor 10.1.13.1 description srl01
 neighbor 10.1.23.1 remote-as 65001
 neighbor 10.1.23.1 description srl02
 !
 address-family ipv4 unicast
  network 10.0.0.3/32
  neighbor 10.1.13.1 activate
  neighbor 10.1.23.1 activate
 exit-address-family
!
line vty
!
