[srlinux]
srl01 ansible_host=172.20.20.11 router_id=10.0.0.1
srl02 ansible_host=172.20.20.12 router_id=10.0.0.2

[frr]
frr01 ansible_host=172.20.20.13 router_id=10.0.0.3

[backbone:children]
srlinux
frr
