---
- name: Reload FRR configuration
  ansible.builtin.command:
    cmd: /usr/lib/frr/frr-reload.py --reload /etc/frr/frr.conf
  register: frr_reload
  changed_when: true
  failed_when: frr_reload.rc != 0
